kind: Deployment
apiVersion: apps/v1
metadata:
  name: expos-admin-bootsrap
  namespace: dap-demo-env
  labels:
    app: expos-admin-bootsrap
  annotations:
    deployment.kubernetes.io/revision: '22'
    kubesphere.io/creator: admin
    kubesphere.io/description: 演示环境系统管理
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expos-admin-bootsrap
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: expos-admin-bootsrap
      annotations:
        kubesphere.io/restartedAt: '2022-10-19T12:23:33.270Z'
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-wkf0vy
          configMap:
            name: dap-expos-conf
            items:
              - key: bootstrap-demo.yml
                path: bootstrap-demo.yml
            defaultMode: 420
      containers:
        - name: container-expos-admin
          image: >-
            harbor.dap.local/demo/expos-admin-bootstrap:1.0.4-SNAPSHOT-20221019125801
          ports:
            - name: http-9080
              containerPort: 9080
              protocol: TCP
          env:
            - name: envType
              value: demo
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-wkf0vy
              readOnly: true
              mountPath: /opt/expos-admin-bootstrap/conf/bootstrap-demo.yml
              subPath: bootstrap-demo.yml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.191.22.162
          hostnames:
            - lf-319-186
        - ip: 10.191.22.163
          hostnames:
            - lf-319-187
        - ip: 10.191.22.164
          hostnames:
            - lf-319-189
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
