kind: Deployment
apiVersion: apps/v1
metadata:
  name: expos-workflow-bootstrap
  namespace: dap-test-env
  labels:
    app: expos-workflow-bootstrap
  annotations:
    deployment.kubernetes.io/revision: '22'
    kubesphere.io/creator: admin
    kubesphere.io/description: 测试环境工单管理
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expos-workflow-bootstrap
  template:
    metadata:
      labels:
        app: expos-workflow-bootstrap
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-conf
          configMap:
            name: dap-expos-conf
            items:
              - key: bootstrap-test.yml
                path: bootstrap-test.yml
            defaultMode: 420
      containers:
        - name: container-expos-workflow
          image: >-
            $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BRANCH_NAME-$BUILD_NUMBER
          ports:
            - name: http-8081
              containerPort: 8081
              protocol: TCP
          env:
            - name: envType
              value: test
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-conf
              readOnly: true
              mountPath: /opt/workflow-bootstrap/conf/bootstrap-test.yml
              subPath: bootstrap-test.yml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.191.22.162
          hostnames:
            - lf-319-186
        - ip: 10.191.22.163
          hostnames:
            - lf-319-187
        - ip: 10.191.22.164
          hostnames:
            - lf-319-189
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
